version: "3.9"

services:
  backend:
    container_name: backend-app
    image: authjwt:latest
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=db:3306
      - DB_NAME=authjwt
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - JWT_SECRET=123abc123
      - PROFILE=test

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: authjwt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s