version: "3.9"

services:
    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_DATABASE: authjwt
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"